apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: opencti-worker
  name: opencti-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: opencti-worker
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: opencti-worker
    spec:
      containers:
        - env:
            - name: WORKER_LOG_LEVEL
              value: info
            - name: OPENCTI_TOKEN
              value: {{ .Values.opencti.APP__ADMIN__TOKEN }}
            - name: OPENCTI_URL
              value: {{ .Values.opencti.APP__BASE_URL}}
          image: {{ .Values.image.repository }}
          name: opencti-worker
          resources: {}
      restartPolicy: Always
status: {}